version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      - VITE_API_URL=${VITE_API_URL}
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    env_file: .env
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
