services:
  frontend:
    build:
      context: ./frontend
    expose:
      - "3000" # matches the server port
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    environment:
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://localhost:8000/health', timeout=2)\n  sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro # <— override default
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped
