from fastapi import APIRouter

from .crud import router as crud_router
from .bulk import router as bulk_router
from .team import router as team_router
from .milestones import router as milestones_router
from .events import router as events_router

router = APIRouter()
router.include_router(crud_router)        # /projects ...
router.include_router(bulk_router)        # /projects/bulk ...
router.include_router(team_router)        # /projects/{id}/team ...
router.include_router(milestones_router)  # /projects/{id}/milestones ...
router.include_router(events_router)      # /projects/{id}/events ...
